apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-openbsw-leos

namePrefix: leos-

commonLabels:
  minbzk.github.io/name: leos

buildMetadata: [originAnnotations]


resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
